### ISSUE TITLE
Difference between == and === in JS

### ISSUE THREAD

**Issue by utkarsh-shekhar** [utkarsh-shekhar/basic-programs#23]
This is for git beginners.

Please add a program demonstrating difference between == and === in Javascript. See readme for the structure and naming your file.

Do let me know if anything is not clear.

**Comment by ChrisSte** [comment]
I would like to to this.

**Comment by utkarsh-shekhar** [comment]
@ChrisSte Sure! :)

**Comment by HJain13** [comment]
Pull Request #29 addresses this issue, Please accept the PR

**Comment by utkarsh-shekhar** [comment]
@ChrisSte Apologies but this has already been done. Can you please work on some other pending issue, maybe [this](https://github.com/utkarsh-shekhar/basic-programs/issues/32)?

**Comment by utkarsh-shekhar** [comment]
Closing this issue
