### ISSUE TITLE
Add palindrome function in python

### ISSUE THREAD

**Issue by KaveeshBaddage** [utkarsh-shekhar/basic-programs#72]
I started work on this

**Comment by KaveeshBaddage** [comment]
Added a pull request to solve this issue. Kindly request to check and accept this pull request.
https://github.com/utkarsh-shekhar/basic-programs/pull/73

**Comment by utkarsh-shekhar** [comment]
Merged this PR

**Comment by utkarsh-shekhar** [comment]
Closing this issue.
